### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pukkamustard** [hyper-systems/ocaml-coap#5]
Very nice project!

Are you considering releasing this as open-source software? If yes, under which license and could you add the license information to the repo?

**Comment by rizo** [comment]
Hi @pukkamustard! I added a license file: https://github.com/hyper-systems/ocaml-coap/blob/main/LICENSE.md

You are free to use the project in any way you see fit :)

By the way, we have some improvements planned for this library soon, so stay tuned.
